version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/frontend'
    schedule:
      interval: 'weekly'
    assignees:
      - 'elgansayer'

  - package-ecosystem: 'npm'
    directory: '/backend'
    schedule:
      interval: 'weekly'
    assignees:
      - 'elgansayer'

  - package-ecosystem: 'npm'
    directory: '/admin-portal'
    schedule:
      interval: 'weekly'
    assignees:
      - 'elgansayer'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    assignees:
      - 'elgansayer'
