import eslint from '@eslint/js';
import tseslint from 'typescript-eslint';
import angular from 'angular-eslint';

export default tseslint.config(
  {
    files: ['**/*.ts'],
    extends: [
      eslint.configs.recommended,
      ...tseslint.configs.recommended,
      ...angular.configs.tsRecommended,
    ],
    processor: angular.processInlineTemplates,
    rules: {
      'no-console': ['error', { allow: ['warn', 'error'] }],
      '@typescript-eslint/no-explicit-any': 'error',
      '@angular-eslint/directive-selector': [
        'error',
        {
          type: 'attribute',
          prefix: 'app',
          style: 'camelCase',
        },
      ],
      '@angular-eslint/component-selector': [
        'error',
        {
          type: 'element',
          prefix: 'app',
          style: 'kebab-case',
        },
      ],
      '@angular-eslint/prefer-host-metadata-property': 'error',
      '@typescript-eslint/no-unused-vars': ['error', { argsIgnorePattern: '^_' }],
    },
  },
  {
    files: ['**/*.spec.ts', '**/*.e2e-spec.ts', '**/*.cy.ts'],
    rules: {
      'no-restricted-syntax': 'off',
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/no-unused-expressions': 'off',
      'no-console': 'off',
    },
  },
  {
    // Vendored spartan/ui (Helm) components, generated by `ng g @spartan-ng/cli:ui` and
    // meant to be re-generated/updated the same way going forward - keep upstream `hlm-`
    // selectors and the `class` input alias (both intrinsic to Helm's public API) rather
    // than renaming, which would fork this code away from `spartan.ng` docs/updates.
    files: ['src/app/components/ui/**/*.ts'],
    rules: {
      '@angular-eslint/directive-selector': 'off',
      '@angular-eslint/component-selector': 'off',
      '@angular-eslint/no-input-rename': 'off',
    },
  },
  {
    files: ['**/*.ts'],
    ignores: ['**/*.spec.ts', '**/*.e2e-spec.ts', '**/*.cy.ts'],
    rules: {
      'no-restricted-syntax': [
        'warn',
        {
          selector: 'TSAsExpression',
          message:
            'Type assertions (as) are banned in production code. Use type narrowing, type guards, or schema validation (Zod) instead. Migrate existing casts before upgrading this to error.',
        },
      ],
    },
  },
  {
    files: ['**/*.html'],
    extends: [...angular.configs.templateRecommended, ...angular.configs.templateAccessibility],
    rules: {
      '@angular-eslint/template/label-has-associated-control': [
        'error',
        {
          controlComponents: ['hlm-checkbox', 'hlm-radio', 'hlm-native-select'],
        },
      ],
      // appA11yClickable's host bindings add the keydown.enter/keydown.space
      // handlers this rule looks for, but they live on the directive's own
      // metadata, invisible to the template AST this rule inspects.
      '@angular-eslint/template/click-events-have-key-events': [
        'error',
        {
          ignoreWithDirectives: ['appA11yClickable'],
        },
      ],
    },
  },
);
