#!/bin/bash
cat frontend/src/app/components/visual-diff/visual-diff.component.ts | sed -e 's/import { Component, computed, input } from '\''@angular\/core'\'';/import { Component, computed, input, inject, signal } from '\''@angular\/core'\'';\nimport { VocabularyStore } from '\''..\/..\/services\/vocabulary.store'\'';\nimport { ToastService } from '\''..\/..\/services\/toast.service'\'';\nimport { I18nService } from '\''..\/..\/services\/i18n.service'\'';/g' > temp.ts
mv temp.ts frontend/src/app/components/visual-diff/visual-diff.component.ts

cat frontend/src/app/components/visual-diff/visual-diff.component.ts | sed -e 's/export class VisualDiffComponent {/export class VisualDiffComponent {\n  readonly vocabStore = inject(VocabularyStore);\n  readonly toast = inject(ToastService);\n  readonly i18n = inject(I18nService);\n\n  readonly showTranslation = signal(false);\n  readonly translationText = signal<string | null>(null);\n  readonly translating = signal(false);\n\n  async toggleTranslation(): Promise<void> {\n    if (this.showTranslation()) {\n      this.showTranslation.set(false);\n      return;\n    }\n    if (this.translationText()) {\n      this.showTranslation.set(true);\n      return;\n    }\n    if (!this.explanation()) return;\n\n    this.translating.set(true);\n    try {\n      const result = await this.vocabStore.translateWordOrSentence(this.explanation()!, '\''en'\'');\n      this.translationText.set(result.translated_text);\n      this.showTranslation.set(true);\n    } catch {\n      this.toast.showToast('\''Failed to translate'\'', '\''error'\'');\n    } finally {\n      this.translating.set(false);\n    }\n  }\n\n  async saveToSrs(): Promise<void> {\n    try {\n      await this.vocabStore.saveWord({\n        word_token: this.corrected(),\n        translation: this.explanation() || this.original(),\n        original_context: this.corrected(),\n      });\n      this.toast.showToast(this.i18n.translate('\''visual_diff.srsSaved'\'' || '\''Saved to SRS'\''), '\''success'\'');\n    } catch {\n      this.toast.showToast(this.i18n.translate('\''visual_diff.srsError'\'' || '\''Failed to save to SRS'\''), '\''error'\'');\n    }\n  }/g' > temp.ts
mv temp.ts frontend/src/app/components/visual-diff/visual-diff.component.ts

cat frontend/src/app/components/visual-diff/visual-diff.component.html | sed -e 's/{{ explanation() }}/{{ explanation() }}\n      <div class="flex items-center gap-2 mt-2">\n        <button (click)="toggleTranslation()" class="text-[10px] flex items-center gap-1 text-neon-blue hover:underline">\n          @if (translating()) {\n            <span>⏳ Translating...<\/span>\n          } @else {\n            <span>🌐 {{ showTranslation() ? ( '\''moments.hideTranslation'\'' | t ) : ( '\''moments.translate'\'' | t ) }}<\/span>\n          }\n        <\/button>\n      <\/div>\n      @if (showTranslation() && translationText()) {\n        <div class="mt-2 text-xs text-text-primary italic border-l-2 border-neon-blue\/50 pl-2">\n          {{ translationText() }}\n        <\/div>\n      }/g' > temp.html
mv temp.html frontend/src/app/components/visual-diff/visual-diff.component.html

cat frontend/src/app/components/visual-diff/visual-diff.component.html | sed -e 's/<\/div>\n<\/div>/<\/div>\n  <div class="mt-3 flex justify-end">\n    <button (click)="saveToSrs()" class="text-xs font-bold bg-surface-200 text-text-primary hover:bg-surface-300 px-3 py-1.5 rounded-full flex items-center gap-1.5 transition-colors shadow-sm">\n      📚 Save to SRS\n    <\/button>\n  <\/div>\n<\/div>/g' > temp.html
mv temp.html frontend/src/app/components/visual-diff/visual-diff.component.html
