export const PREDEFINED_HOBBIES: string[] = [
  'reading',
  'writing',
  'travelling',
  'singing',
  'cooking',
  'drawing',
  'photography',
  'gaming',
  'hiking',
  'cycling',
  'running',
  'yoga',
  'dancing',
  'painting',
  'knitting',
  'gardening',
  'music',
  'movies',
  'sports',
  'fishing',
  'board games',
  'volunteering',
  'learning languages',
];

export const PREDEFINED_INTERESTS: string[] = [
  'technology',
  'fashion',
  'food',
  'travel',
  'art',
  'science',
  'history',
  'philosophy',
  'politics',
  'environment',
  'fitness',
  'wellness',
  'business',
  'entrepreneurship',
  'education',
  'psychology',
  'spirituality',
  'design',
  'music',
  'movies',
  'books',
  'anime',
  'coding',
  'space',
];
