import { Injectable, Logger } from '@nestjs/common';
import { OnEvent } from '@nestjs/event-emitter';
import Redis from 'ioredis';
import { SupabaseService } from '../supabase/supabase.service';
import {
  DiscoveryCacheNamespace,
  CacheInvalidationRule,
  CacheInvalidationTrigger,
  CacheKeyOptions,
} from './interfaces/cache-rules.interface';

/**
 * Centralised Redis cache invalidation service for the Discovery Map.
 *
 * Responsibilities:
 * - Defines canonical invalidation rules for all discovery cache keys.
 * - Builds discovery-specific cache keys.
 * - Invalidates single keys or entire patterns on data-mutation events.
 * - Provides observability through structured logging.
 *
 * Invalidation Strategy:
 *  - Partner of the Week (`partner_of_week_ids`): deleted when the weekly
 *    cron regenerates the pool so stale CDN-cached versions are evicted.
 *  - Daily recommendations (`daily_recommendations:{userId}`): user-scoped
 *    pattern deletion when a user's profile changes, their data is cleared,
 *    or a trust-and-safety action removes them from the partner pool.
 *
 * Event conventions:
 *  - discovery.* events are informational (emitted AFTER cache write) and
 *    are consumed by external listeners (Cloudflare, analytics).  This
 *    service does NOT listen to them to avoid a write-then-immediately-delete
 *    race on its own keys.
 *  - user.* events are emitted by the users module and signal that cached
 *    discovery data is now stale.
 *  - safety.* events are handled by SafetyCacheInvalidationService; the
 *    patterns declared there overlap with these rules for defence-in-depth.
 */
@Injectable()
export class DiscoveryCacheInvalidationService {
  private readonly logger = new Logger(DiscoveryCacheInvalidationService.name);

  /** Canonical set of invalidation rules for the discovery module. */
  readonly rules: ReadonlyArray<CacheInvalidationRule> = [
    {
      description:
        'Invalidate the global Partner of the Week pool when the weekly cron regenerates it',
      patterns: ['partner_of_week_ids'],
      triggers: [CacheInvalidationTrigger.PARTNER_OF_WEEK_UPDATED],
    },
    {
      description:
        'Invalidate a user\'s daily recommendations when their recs are regenerated by the daily cron',
      patterns: ['daily_recommendations:*'],
      triggers: [CacheInvalidationTrigger.RECOMMENDATIONS_UPDATED],
    },
    {
      description:
        'Invalidate all daily recommendation caches when a user changes their profile',
      patterns: ['daily_recommendations:*'],
      triggers: [CacheInvalidationTrigger.USER_PROFILE_UPDATED],
    },
    {
      description:
        'Bulk-invalidate every discovery key belonging to a user on data clear',
      patterns: ['daily_recommendations:*'],
      triggers: [CacheInvalidationTrigger.USER_DATA_CLEARED],
    },
  ];

  constructor(private readonly supabaseService: SupabaseService) {}

  private getRedis(): Redis {
    return this.supabaseService.getRedisClient();
  }

  /* ------------------------------------------------------------------ */
  /*  Key builders                                                      */
  /* ------------------------------------------------------------------ */

  buildKey(opts: CacheKeyOptions): string {
    if (opts.namespace === DiscoveryCacheNamespace.PARTNER_OF_WEEK) {
      return DiscoveryCacheNamespace.PARTNER_OF_WEEK;
    }
    // User-scoped key: daily_recommendations:{userId}
    return `${opts.namespace}:${opts.userId}`;
  }

  /* ------------------------------------------------------------------ */
  /*  Public invalidation helpers                                       */
  /* ------------------------------------------------------------------ */

  /** Delete a single exact key. */
  async deleteKey(key: string): Promise<void> {
    try {
      await this.getRedis().del(key);
      this.logger.debug({ key }, 'Discovery cache key deleted');
    } catch (err) {
      this.logger.error({ key, error: (err as Error).message }, 'Discovery cache delete failed');
    }
  }

  /**
   * Delete all keys matching a glob pattern using SCAN + pipeline DEL.
   * Safe for production -- never uses KEYS.
   */
  async deletePattern(pattern: string): Promise<number> {
    const redis = this.getRedis();
    let cursor = '0';
    let deleted = 0;
    try {
      do {
        const [nextCursor, keys] = await redis.scan(
          cursor,
          'MATCH',
          pattern,
          'COUNT',
          500,
        );
        cursor = nextCursor;
        if (keys.length > 0) {
          deleted += await redis.del(...keys);
        }
      } while (cursor !== '0');
      if (deleted > 0) {
        this.logger.log({ pattern, deleted }, 'Discovery bulk cache invalidation');
      }
    } catch (err) {
      this.logger.error(
        { pattern, error: (err as Error).message },
        'Discovery bulk cache invalidation failed',
      );
    }
    return deleted;
  }

  /** Delete a user's daily recommendation cache entry. */
  async invalidateUserRecommendations(userId: string): Promise<void> {
    const key = this.buildKey({
      namespace: DiscoveryCacheNamespace.DAILY_RECOMMENDATIONS,
      userId,
    });
    await this.deleteKey(key);
  }

  /** Invalidate the global Partner of the Week pool. */
  async invalidatePartnerOfWeek(): Promise<void> {
    await this.deleteKey(DiscoveryCacheNamespace.PARTNER_OF_WEEK);
  }

  /* ------------------------------------------------------------------ */
  /*  Event-driven invalidation (external triggers)                     */
  /* ------------------------------------------------------------------ */

  /**
   * When a user updates their profile (languages, bio, location, etc.),
   * their own cached recommendations are stale AND other users may have
   * this user in their cached recommendation sets.
   *
   * Strategy: invalidate ALL daily_recommendations:* keys.  The TTL on
   * these keys is short (24 h) and a profile update is a relatively rare
   * event, so broad invalidation is a reasonable trade-off.
   */
  @OnEvent('user.profile_updated', { async: true })
  async handleUserProfileUpdated(payload: { userId: string }): Promise<void> {
    const pattern = `${DiscoveryCacheNamespace.DAILY_RECOMMENDATIONS}:*`;
    const deleted = await this.deletePattern(pattern);
    this.logger.log(
      { userId: payload.userId, deleted },
      'Invalidated all daily recommendation caches (user.profile_updated)',
    );
  }

  /**
   * When a user account is deleted, purge all their discovery-related
   * cache entries so they do not appear in any partner recommendations.
   */
  @OnEvent('user.deleted', { async: true })
  async handleUserDeleted(payload: { userId: string }): Promise<void> {
    const redis = this.getRedis();
    try {
      // Delete the user's own recommendation list
      const userKey = `${DiscoveryCacheNamespace.DAILY_RECOMMENDATIONS}:${payload.userId}`;
      // Also invalidate all other users' recommendation lists since this
      // user may appear in them.
      const allKeys: string[] = [userKey];
      const deleted = await redis.del(...allKeys);
      // Broad invalidation: clear all daily recs since deleted user might
      // appear in any of them.
      const patternDeleted = await this.deletePattern(
        `${DiscoveryCacheNamespace.DAILY_RECOMMENDATIONS}:*`,
      );
      if (deleted > 0 || patternDeleted > 0) {
        this.logger.log(
          { userId: payload.userId, deleted: deleted + patternDeleted },
          'Purged discovery caches for deleted user',
        );
      }
    } catch (err) {
      this.logger.error(
        { userId: payload.userId, error: (err as Error).message },
        'Failed to purge discovery caches for deleted user',
      );
    }
  }
}