import { TestBed } from '@angular/core/testing';
import { provideHttpClient } from '@angular/common/http';
import { HttpTestingController, provideHttpClientTesting } from '@angular/common/http/testing';
import { describe, it, expect, beforeEach, afterEach, vi } from 'vitest';
import { DiscoveryMapErrorBoundaryComponent } from './discovery-map-error-boundary.component';

/** Helper to flush any pending HTTP error-reporting POST requests generated by captureError. */
function flushErrorRequest(httpTesting: HttpTestingController): void {
  const req = httpTesting.match('/api/analytics/client-error');
  for (const r of req) {
    r.flush({ status: 'logged' });
  }
}

describe('DiscoveryMapErrorBoundaryComponent', () => {
  let httpTesting: HttpTestingController;

  beforeEach(() => {
    TestBed.resetTestingModule();
    TestBed.configureTestingModule({
      imports: [DiscoveryMapErrorBoundaryComponent],
      providers: [
        provideHttpClient(),
        provideHttpClientTesting(),
      ],
    });

    httpTesting = TestBed.inject(HttpTestingController);
  });

  afterEach(() => {
    httpTesting.verify();
  });

  it('should create the component', () => {
    const fixture = TestBed.createComponent(DiscoveryMapErrorBoundaryComponent);
    const component = fixture.componentInstance;
    expect(component).toBeDefined();
  });

  it('should display fallback UI when an error is captured', () => {
    const fixture = TestBed.createComponent(DiscoveryMapErrorBoundaryComponent);
    const component = fixture.componentInstance;
    fixture.detectChanges();

    component.captureError(new Error('Discovery map rendering crash'));
    fixture.detectChanges();

    const compiled = fixture.nativeElement as HTMLElement;
    expect(compiled.querySelector('h2')?.textContent).toContain('discoveryMapErrorBoundary.title');
    expect(compiled.textContent).toContain('Discovery map rendering crash');

    flushErrorRequest(httpTesting);
  });

  it('should reset error state when resetError is called', () => {
    const fixture = TestBed.createComponent(DiscoveryMapErrorBoundaryComponent);
    const component = fixture.componentInstance;
    fixture.detectChanges();

    component.captureError(new Error('Temporary discovery error'));
    expect(component.hasError()).toBe(true);

    component.resetError();
    expect(component.hasError()).toBe(false);
    expect(component.errorSummary()).toBe('');
    expect(component.errorCount()).toBe(0);

    flushErrorRequest(httpTesting);
  });

  it('should increment error count on repeated errors', () => {
    const fixture = TestBed.createComponent(DiscoveryMapErrorBoundaryComponent);
    const component = fixture.componentInstance;
    fixture.detectChanges();

    component.captureError(new Error('First error'));
    expect(component.errorCount()).toBe(1);

    component.captureError(new Error('Second error'));
    expect(component.errorCount()).toBe(2);

    component.resetError();
    expect(component.errorCount()).toBe(0);

    flushErrorRequest(httpTesting);
    flushErrorRequest(httpTesting);
  });

  it('should emit retry event on reset', () => {
    const fixture = TestBed.createComponent(DiscoveryMapErrorBoundaryComponent);
    const component = fixture.componentInstance;
    fixture.detectChanges();

    const retrySpy = vi.fn();
    component.retry.subscribe(retrySpy);

    component.captureError(new Error('Test'));
    component.resetError();

    expect(retrySpy).toHaveBeenCalled();

    flushErrorRequest(httpTesting);
  });

  it('should report crash to global error handler and show reported message', () => {
    const fixture = TestBed.createComponent(DiscoveryMapErrorBoundaryComponent);
    const component = fixture.componentInstance;
    fixture.detectChanges();

    component.captureError(new Error('Map tile loading failure'));
    fixture.detectChanges();

    // Flush captureError's POST before calling reportCrash to avoid ambiguity
    flushErrorRequest(httpTesting);

    component.reportCrash();
    fixture.detectChanges();

    expect(component.reportedMessage()).toBe(true);
    const compiled = fixture.nativeElement as HTMLElement;
    expect(compiled.textContent).toContain('discoveryMapErrorBoundary.reportedMessage');

    // Verify error sent to the global error handler via analytics endpoint
    const req = httpTesting.expectOne('/api/analytics/client-error');
    expect(req.request.method).toBe('POST');
    const body = req.request.body as Record<string, unknown>;
    expect(body['message']).toContain('Manual report');
    expect(body['name']).toBe('DiscoveryMapManualReport');
    req.flush({ status: 'logged' });
  });

  it('should send error to analytics when captureError is called', () => {
    const fixture = TestBed.createComponent(DiscoveryMapErrorBoundaryComponent);
    const component = fixture.componentInstance;
    fixture.detectChanges();

    component.captureError(new Error('Partner search rendering failure'));
    fixture.detectChanges();

    const req = httpTesting.expectOne('/api/analytics/client-error');
    expect(req.request.method).toBe('POST');
    const body = req.request.body as Record<string, unknown>;
    expect(body['message']).toContain('Partner search rendering failure');
    expect(body['name']).toBe('DiscoveryMapError');
    req.flush({ status: 'logged' });
  });

  it('should not show fallback UI when hasError is false', () => {
    const fixture = TestBed.createComponent(DiscoveryMapErrorBoundaryComponent);
    fixture.detectChanges();

    const compiled = fixture.nativeElement as HTMLElement;
    expect(compiled.querySelector('h2')).toBeNull();
  });

  it('should use default fallback message for errors with empty message', () => {
    const fixture = TestBed.createComponent(DiscoveryMapErrorBoundaryComponent);
    const component = fixture.componentInstance;
    fixture.detectChanges();

    // Create an Error object with no message argument
    const emptyError = new Error();
    emptyError.message = '';
    component.captureError(emptyError);
    fixture.detectChanges();

    expect(component.errorSummary()).toBe('Unknown discovery map error');

    flushErrorRequest(httpTesting);
  });

  it('should use provided message override', () => {
    const fixture = TestBed.createComponent(DiscoveryMapErrorBoundaryComponent);
    const component = fixture.componentInstance;
    fixture.detectChanges();

    component.captureError(new Error('Original'), 'Custom error message');
    fixture.detectChanges();

    expect(component.errorSummary()).toBe('Custom error message');

    flushErrorRequest(httpTesting);
  });

  it('should show report button by default when error occurs', () => {
    const fixture = TestBed.createComponent(DiscoveryMapErrorBoundaryComponent);
    const component = fixture.componentInstance;
    fixture.detectChanges();

    // Default: showReport() returns true (default input value)
    component.captureError(new Error('Test error'));
    fixture.detectChanges();

    const compiled = fixture.nativeElement as HTMLElement;
    const buttons = compiled.querySelectorAll('button');
    const reportButton = Array.from(buttons).find(
      (btn) => btn.textContent?.includes('discoveryMapErrorBoundary.report'),
    );
    expect(reportButton).toBeDefined();

    flushErrorRequest(httpTesting);
  });
});