export const MOCK_LINKED_ACCOUNTS = [
  {
    user_id: 'fake-1',
    provider: 'google',
    name: 'sakura@gmail.com',
    active: true,
    created_at: '2024-01-15T00:00:00Z',
  },
  {
    user_id: 'fake-1',
    provider: 'email',
    name: 'sakura1@example.com',
    active: true,
    created_at: '2024-01-10T00:00:00Z',
  },
  {
    user_id: 'fake-2',
    provider: 'facebook',
    name: 'Minjun Kim',
    active: true,
    created_at: '2024-02-20T00:00:00Z',
  },
  {
    user_id: 'fake-2',
    provider: 'twitter',
    name: '@minjun_dev',
    active: true,
    created_at: '2024-02-15T00:00:00Z',
  },
  {
    user_id: 'fake-3',
    provider: 'apple',
    name: 'emma@icloud.com',
    active: true,
    created_at: '2024-03-01T00:00:00Z',
  },
  {
    user_id: 'fake-3',
    provider: 'google',
    name: 'emma.writes@gmail.com',
    active: false,
    created_at: '2024-03-05T00:00:00Z',
  },
  {
    user_id: 'fake-4',
    provider: 'email',
    name: 'liam@example.com',
    active: true,
    created_at: '2024-04-01T00:00:00Z',
  },
  {
    user_id: 'fake-5',
    provider: 'google',
    name: 'olivia@gmail.com',
    active: true,
    created_at: '2024-04-10T00:00:00Z',
  },
  {
    user_id: 'fake-5',
    provider: 'apple',
    name: 'olivia@icloud.com',
    active: true,
    created_at: '2024-04-05T00:00:00Z',
  },
  {
    user_id: 'fake-5',
    provider: 'twitter',
    name: '@olivia_creator',
    active: true,
    created_at: '2024-04-08T00:00:00Z',
  },
];

export const MOCK_FLASHCARDS = [
  {
    id: 'mock-flashcard-1',
    user_id: 'mock-user',
    word_token: 'abundant',
    original_context: 'The rainforest has an abundant variety of species.',
    translation: 'abundant',
    definition: 'existing or available in large quantities; plentiful',
    pronunciation_url: null,
    srs_level: 1,
    easiness_factor: 2.5,
    repetitions: 1,
    interval_days: 3,
    next_review_at: new Date(Date.now() - 3600000).toISOString(),
    created_at: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: 'mock-flashcard-2',
    user_id: 'mock-user',
    word_token: 'ephemeral',
    original_context: 'The beauty of cherry blossoms is ephemeral.',
    translation: 'ephemeral',
    definition: 'lasting for a very short time',
    pronunciation_url: null,
    srs_level: 2,
    easiness_factor: 2.6,
    repetitions: 2,
    interval_days: 7,
    next_review_at: new Date(Date.now() + 86400000).toISOString(),
    created_at: new Date(Date.now() - 172800000).toISOString(),
  },
  {
    id: 'mock-flashcard-3',
    user_id: 'mock-user',
    word_token: 'serendipity',
    original_context: 'Finding that book was pure serendipity.',
    translation: 'serendipity',
    definition: 'the occurrence of events by chance in a happy way',
    pronunciation_url: null,
    srs_level: 3,
    easiness_factor: 2.7,
    repetitions: 3,
    interval_days: 14,
    next_review_at: new Date(Date.now() - 7200000).toISOString(),
    created_at: new Date(Date.now() - 259200000).toISOString(),
  },
  {
    id: 'mock-flashcard-4',
    user_id: 'mock-user',
    word_token: 'eloquent',
    original_context: 'She gave an eloquent speech at the ceremony.',
    translation: 'eloquent',
    definition: 'fluent or persuasive in speaking or writing',
    pronunciation_url: null,
    srs_level: 0,
    easiness_factor: 2.5,
    repetitions: 0,
    interval_days: 0,
    next_review_at: new Date().toISOString(),
    created_at: new Date(Date.now() - 43200000).toISOString(),
  },
  {
    id: 'mock-flashcard-5',
    user_id: 'mock-user',
    word_token: 'nostalgia',
    original_context: 'The old song filled her with nostalgia.',
    translation: 'nostalgia',
    definition: 'a sentimental longing for the past',
    pronunciation_url: null,
    srs_level: 4,
    easiness_factor: 2.9,
    repetitions: 5,
    interval_days: 30,
    next_review_at: new Date(Date.now() + 604800000).toISOString(),
    created_at: new Date(Date.now() - 604800000).toISOString(),
  },
];

export const MOCK_FLASHCARD_SUGGESTIONS = [
  'abundant',
  'ephemeral',
  'serendipity',
  'eloquent',
  'nostalgia',
  'ubiquitous',
  'ambiguous',
  'pragmatic',
  'resilient',
  'conundrum',
];

export const MOCK_USERS = Array.from({ length: 150 }, (_, i) => {
  const nativeLangs = ['en', 'es', 'fr', 'de', 'ja', 'ko', 'zh', 'no'];
  const targetLangs = ['en', 'es', 'fr', 'de', 'ja', 'ko', 'zh', 'no'];

  const native = nativeLangs[Math.floor(Math.random() * nativeLangs.length)];
  const targets = [targetLangs[Math.floor(Math.random() * targetLangs.length)]];
  if (Math.random() > 0.5 && targets[0] !== 'en') targets.push('en');

  const names = [
    'Sakura',
    'Min-jun',
    'Emma',
    'Liam',
    'Olivia',
    'Noah',
    'Ava',
    'Oliver',
    'Isabella',
    'Elijah',
    'Lars',
    'Astrid',
    'Yuki',
    'Kenji',
    'Satoshi',
    'Mei',
    'Hiroshi',
    'Jin',
    'Ji-eun',
    'Hassan',
    'Fatima',
    'Omar',
    'Aisha',
    'Carlos',
    'Maria',
  ];
  const name = names[Math.floor(Math.random() * names.length)];

  return {
    id: `fake-${i + 1}`,
    display_name: `${name}${i + 1}`,
    native_languages: native,
    target_languages: targets,
    bio_text: `Hi! I want to learn ${targets.join(', ').toUpperCase()} and I can teach ${native.toUpperCase()}. Let's chat!`,
    avatar_url: `https://i.pravatar.cc/150?u=fake-${i + 1}`,
    is_vip: Math.random() > 0.8,
    study_streak_days: Math.floor(Math.random() * 50),
    correction_ratio: Number((0.5 + Math.random() * 0.5).toFixed(2)),
    is_serious_learner: Math.random() > 0.6,
    created_at: new Date().toISOString(),
  };
});
