
import { Deck } from './decks/interfaces/deck.interface';

export const MOCK_DECKS: Deck[] = [
  {
    id: 'mock-deck-1',
    user_id: 'fake-1',
    name: 'Essential Spanish Verbs',
    description: 'Core verbs for everyday conversation',
    colour: '#6366f1',
    icon: '📚',
    card_count: 12,
    created_at: new Date(Date.now() - 7 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'mock-deck-2',
    user_id: 'fake-1',
    name: 'Travel Phrases',
    description: 'Must-know phrases for travelling',
    colour: '#ec4899',
    icon: '✈️',
    card_count: 8,
    created_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'mock-deck-3',
    user_id: 'fake-1',
    name: 'Food & Cooking',
    description: null,
    colour: '#f59e0b',
    icon: '🍳',
    card_count: 5,
    created_at: new Date(Date.now() - 14 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'mock-deck-4',
    user_id: 'fake-1',
    name: 'Business Japanese',
    description: 'Formal expressions and keigo',
    colour: '#10b981',
    icon: '💼',
    card_count: 20,
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'mock-deck-5',
    user_id: 'fake-1',
    name: 'Slang & Idioms',
    description: 'Sound like a native speaker',
    colour: '#8b5cf6',
    icon: '💬',
    card_count: 15,
    created_at: new Date(Date.now() - 21 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
];
