import type { ChatMessage } from '../../services/chat.service';

export type DeliveryStatus = NonNullable<ChatMessage['delivery_status']>;

export interface ChatRoomRealtimeResult {
  messages: ChatMessage[];
  incomingMessageToMarkRead: ChatMessage | null;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function isDeliveryStatus(value: unknown): value is DeliveryStatus {
  return value === 'sent' || value === 'delivered' || value === 'read';
}

function isSystemEvent(value: unknown): value is NonNullable<ChatMessage['system_event']> {
  if (!isRecord(value)) return false;
  const type = value['type'];
  return typeof type === 'string' && type.length > 0;
}

function isChatMessage(value: unknown): value is ChatMessage {
  if (!isRecord(value)) return false;

  const senderId = value['sender_id'];
  const messageType = value['message_type'];
  const hasRequiredFields =
    typeof value['id'] === 'string' &&
    value['id'].length > 0 &&
    typeof value['room_id'] === 'string' &&
    value['room_id'].length > 0 &&
    typeof senderId === 'string' &&
    typeof messageType === 'string' &&
    typeof value['created_at'] === 'string';

  if (!hasRequiredFields) return false;

  // System messages are ephemeral Centrifugo events generated by the backend.
  // They intentionally use an empty sender_id, so validate their typed event
  // payload instead of applying the non-system sender requirement.
  if (messageType === 'system') {
    return isSystemEvent(value['system_event']);
  }

  return senderId.length > 0;
}

/**
 * Applies one untrusted Centrifugo payload to the current room state.
 *
 * The function is intentionally pure so realtime payload validation, duplicate
 * suppression and delivery-status ordering remain independently testable.
 */
export function applyChatRoomRealtimeEvent(
  messages: ChatMessage[],
  payload: unknown,
  roomId: string,
  currentUserId: string | undefined,
): ChatRoomRealtimeResult {
  const unchanged = { messages, incomingMessageToMarkRead: null };
  if (!isRecord(payload)) return unchanged;

  const message = payload['message'];
  if (isChatMessage(message)) {
    if (message.room_id !== roomId) return unchanged;

    const existingIndex = messages.findIndex((candidate) => candidate.id === message.id);
    const nextMessages = [...messages];
    if (existingIndex >= 0) {
      // Message events are also used for server-side edits/corrections. Merge the
      // authoritative payload rather than appending a duplicate bubble.
      nextMessages[existingIndex] = { ...nextMessages[existingIndex], ...message };
    } else {
      nextMessages.push(message);
    }

    return {
      messages: nextMessages,
      // System events are not persisted chat rows and therefore have no read
      // receipt to acknowledge. Attempting to mark their synthetic IDs as read
      // would issue a failing API request for every realtime system bubble.
      incomingMessageToMarkRead:
        currentUserId &&
        message.message_type !== 'system' &&
        message.sender_id !== currentUserId &&
        message.delivery_status !== 'read'
          ? message
          : null,
    };
  }

  const statusUpdate = payload['status_update'];
  if (isRecord(statusUpdate)) {
    const messageId = statusUpdate['message_id'];
    const deliveryStatus = statusUpdate['delivery_status'];
    if (typeof messageId !== 'string' || !isDeliveryStatus(deliveryStatus)) return unchanged;

    let changed = false;
    const nextMessages = messages.map((candidate) => {
      if (candidate.id !== messageId) return candidate;
      if (candidate.delivery_status === deliveryStatus) return candidate;
      changed = true;
      return { ...candidate, delivery_status: deliveryStatus };
    });

    return {
      messages: changed ? nextMessages : messages,
      incomingMessageToMarkRead: null,
    };
  }

  if (payload['type'] === 'message_deleted' && payload['deleted_for'] === 'everyone') {
    const messageId = payload['message_id'];
    if (typeof messageId !== 'string' || !messages.some((message) => message.id === messageId)) {
      return unchanged;
    }
    return {
      messages: messages.filter((message) => message.id !== messageId),
      incomingMessageToMarkRead: null,
    };
  }

  return unchanged;
}
