INSERT INTO hobby_tags (name, category, icon, target_vocabulary) VALUES
('Cooking', 'Food & Drink', '🍳', '[{"word": "recipe", "translation": "receta", "language": "es"}, {"word": "ingredient", "translation": "ingrediente", "language": "es"}, {"word": "simmer", "translation": "hervir a fuego lento", "language": "es"}, {"word": "chop", "translation": "picar", "language": "es"}, {"word": "bake", "translation": "hornear", "language": "es"}]'),
('Travel', 'Lifestyle', '✈️', '[{"word": "destination", "translation": "destino", "language": "es"}, {"word": "itinerary", "translation": "itinerario", "language": "es"}, {"word": "accommodation", "translation": "alojamiento", "language": "es"}, {"word": "sightseeing", "translation": "turismo", "language": "es"}, {"word": "backpack", "translation": "mochila", "language": "es"}]'),
('Fitness', 'Sports & Health', '💪', '[{"word": "workout", "translation": "entrenamiento", "language": "es"}, {"word": "repetition", "translation": "repetición", "language": "es"}, {"word": "stretch", "translation": "estirar", "language": "es"}, {"word": "endurance", "translation": "resistencia", "language": "es"}, {"word": "nutrition", "translation": "nutrición", "language": "es"}]'),
('Music', 'Arts & Culture', '🎵', '[{"word": "melody", "translation": "melodía", "language": "es"}, {"word": "rhythm", "translation": "ritmo", "language": "es"}, {"word": "instrument", "translation": "instrumento", "language": "es"}, {"word": "concert", "translation": "concierto", "language": "es"}, {"word": "compose", "translation": "componer", "language": "es"}]'),
('Gaming', 'Entertainment', '🎮', '[{"word": "achievement", "translation": "logro", "language": "es"}, {"word": "multiplayer", "translation": "multijugador", "language": "es"}, {"word": "strategy", "translation": "estrategia", "language": "es"}, {"word": "level up", "translation": "subir de nivel", "language": "es"}, {"word": "quest", "translation": "misión", "language": "es"}]'),
('Photography', 'Arts & Culture', '📸', '[{"word": "aperture", "translation": "apertura", "language": "es"}, {"word": "exposure", "translation": "exposición", "language": "es"}, {"word": "composition", "translation": "composición", "language": "es"}, {"word": "landscape", "translation": "paisaje", "language": "es"}, {"word": "portrait", "translation": "retrato", "language": "es"}]'),
('Reading', 'Lifestyle', '📚', '[{"word": "chapter", "translation": "capítulo", "language": "es"}, {"word": "plot", "translation": "trama", "language": "es"}, {"word": "character", "translation": "personaje", "language": "es"}, {"word": "novel", "translation": "novela", "language": "es"}, {"word": "genre", "translation": "género", "language": "es"}]'),
('Technology', 'Education', '💻', '[{"word": "algorithm", "translation": "algoritmo", "language": "es"}, {"word": "database", "translation": "base de datos", "language": "es"}, {"word": "debug", "translation": "depurar", "language": "es"}, {"word": "framework", "translation": "marco de trabajo", "language": "es"}, {"word": "encryption", "translation": "cifrado", "language": "es"}]')
ON CONFLICT (name) DO NOTHING;
