export const environment = {
  production: true,
  supabaseUrl: 'https://mock.supabase.co',
  supabaseAnonKey: 'mock-anon-key',
  apiUrl: '/api',
  centrifugoUrl: 'wss://example.com/connection/websocket',
  liveKitUrl: 'wss://livekit.yourdomain.com',
  turnServerUrl: 'turn:turn.yourdomain.com:3478',
  turnUsername: 'guest',
  turnPassword: 'somepassword',
  firebase: {
    apiKey: 'YOUR_API_KEY',
    authDomain: 'YOUR_AUTH_DOMAIN',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_STORAGE_BUCKET',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    appId: 'YOUR_APP_ID',
    vapidKey: 'YOUR_VAPID_KEY',
  },
};
