import { describe, it, expect, beforeEach, vi } from 'vitest';
import { TestBed } from '@angular/core/testing';
import {
  HttpClientTestingModule,
  HttpTestingController,
} from '@angular/common/http/testing';
import { ReadingEngineCrashReportingService } from './reading-engine-crash-reporting.service';
import { AuthService } from './auth.service';

describe('ReadingEngineCrashReportingService', () => {
  let service: ReadingEngineCrashReportingService;
  let httpMock: HttpTestingController;

  beforeEach(async () => {
    const mockAuthService = {
      getAccessToken: vi.fn().mockReturnValue('test-token'),
    };

    await TestBed.configureTestingModule({
      imports: [HttpClientTestingModule],
      providers: [
        ReadingEngineCrashReportingService,
        { provide: AuthService, useValue: mockAuthService },
      ],
    }).compileComponents();

    service = TestBed.inject(ReadingEngineCrashReportingService);
    httpMock = TestBed.inject(HttpTestingController);
  });

  afterEach(() => {
    httpMock.verify();
  });

  it('should be created', () => {
    expect(service).toBeTruthy();
  });

  it('should send crash report with full context', () => {
    const error = new Error('Test crash');
    error.stack =
      'Error: Test crash\n    at Object.<anonymous> (/app/test.ts:42:10)';

    service.reportCrash(error, {
      boundaryContext: 'test-component',
      operation: 'fetchArticles',
      articleLanguage: 'en-GB',
      activeArticleId: 'article-1',
      renderingError: true,
      tokenCount: 42,
    });

    const req = httpMock.expectOne((r) =>
      r.url.includes('/analytics/client-error'),
    );
    expect(req.request.method).toBe('POST');
    expect(req.request.body.metadata.category).toBe('reading-engine');
    expect(req.request.body.metadata.boundaryContext).toBe('test-component');
    expect(req.request.body.metadata.operation).toBe('fetchArticles');
    expect(req.request.body.metadata.articleLanguage).toBe('en-GB');
    expect(req.request.body.metadata.activeArticleId).toBe('article-1');
    expect(req.request.body.metadata.renderingError).toBe(true);
    expect(req.request.body.metadata.tokenCount).toBe(42);
    expect(req.request.body.stackFrames).toBeDefined();
    expect(req.request.body.stackFrames.length).toBeGreaterThan(0);
    req.flush({});
  });

  it('should track recent crashes', () => {
    const error = new Error('Crash 1');
    service.reportCrash(error, { operation: 'op1' });

    const req1 = httpMock.expectOne((r) =>
      r.url.includes('/analytics/client-error'),
    );
    req1.flush({});

    const error2 = new Error('Crash 2');
    service.reportCrash(error2, { operation: 'op2' });

    const req2 = httpMock.expectOne((r) =>
      r.url.includes('/analytics/client-error'),
    );
    req2.flush({});

    expect(service.recentCrashes().length).toBe(2);
    expect(service.recentCrashes()[0].message).toBe('Crash 2');
    expect(service.recentCrashes()[1].message).toBe('Crash 1');
  });

  it('should cap recent crashes at 10', () => {
    for (let i = 0; i < 15; i++) {
      const error = new Error(`Crash ${i}`);
      service.reportCrash(error);
      const req = httpMock.expectOne((r) =>
        r.url.includes('/analytics/client-error'),
      );
      req.flush({});
    }
    expect(service.recentCrashes().length).toBe(10);
  });

  it('should send crash report with minimal context', () => {
    const error = new Error('Minimal crash');

    service.reportCrash(error);

    const req = httpMock.expectOne((r) =>
      r.url.includes('/analytics/client-error'),
    );
    expect(req.request.body.metadata.category).toBe('reading-engine');
    expect(req.request.body.metadata.renderingError).toBe(false);
    req.flush({});
  });

  it('should handle HTTP failures silently', () => {
    const error = new Error('Silent failure');
    const consoleSpy = vi
      .spyOn(console, 'warn')
      .mockImplementation(() => {});

    service.reportCrash(error);

    const req = httpMock.expectOne((r) =>
      r.url.includes('/analytics/client-error'),
    );
    req.error(new ErrorEvent('Network error'));

    // Should not throw
    expect(true).toBe(true);
    consoleSpy.mockRestore();
  });

  it('should wrap call and return result on success', async () => {
    const result = await service.wrapCall('testOp', () =>
      Promise.resolve('success'),
    );
    expect(result).toBe('success');
  });

  it('should wrap call and return null on failure with crash report', async () => {
    const crashSpy = vi.spyOn(service, 'reportCrash');

    const result = await service.wrapCall('failingOp', () =>
      Promise.reject(new Error('Wrapped failure')),
    );

    expect(result).toBeNull();
    expect(crashSpy).toHaveBeenCalledTimes(1);
    const callArgs = crashSpy.mock.calls[0][1];
    expect(callArgs?.operation).toBe('failingOp');

    // Flush HTTP request generated by reportCrash
    const req = httpMock.expectOne((r) =>
      r.url.includes('/analytics/client-error'),
    );
    req.flush({});
  });

  it('should wrap call and handle non-Error throws', async () => {
    const result = await service.wrapCall('stringThrow', () =>
      Promise.reject('string error'),
    );

    expect(result).toBeNull();
    const req = httpMock.expectOne((r) =>
      r.url.includes('/analytics/client-error'),
    );
    req.flush({});
  });
});